# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigService.proto',
  package='com.vsu001.ethernet.core',
  syntax='proto3',
  serialized_options=b'\n com.vsu001.ethernet.core.serviceB\022ConfigServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x43onfigService.proto\x12\x18\x63om.vsu001.ethernet.core\"\x1e\n\x1cGetNeo4jServingConfigRequest\"[\n\x1dGetNeo4jServingConfigResponse\x12\x16\n\x0e\x63onnection_uri\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t2\x9a\x01\n\rConfigService\x12\x88\x01\n\x15GetNeo4jServingConfig\x12\x36.com.vsu001.ethernet.core.GetNeo4jServingConfigRequest\x1a\x37.com.vsu001.ethernet.core.GetNeo4jServingConfigResponseB8\n com.vsu001.ethernet.core.serviceB\x12\x43onfigServiceProtoP\x01\x62\x06proto3'
)




_GETNEO4JSERVINGCONFIGREQUEST = _descriptor.Descriptor(
  name='GetNeo4jServingConfigRequest',
  full_name='com.vsu001.ethernet.core.GetNeo4jServingConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)


_GETNEO4JSERVINGCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetNeo4jServingConfigResponse',
  full_name='com.vsu001.ethernet.core.GetNeo4jServingConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connection_uri', full_name='com.vsu001.ethernet.core.GetNeo4jServingConfigResponse.connection_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='com.vsu001.ethernet.core.GetNeo4jServingConfigResponse.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='com.vsu001.ethernet.core.GetNeo4jServingConfigResponse.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['GetNeo4jServingConfigRequest'] = _GETNEO4JSERVINGCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetNeo4jServingConfigResponse'] = _GETNEO4JSERVINGCONFIGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetNeo4jServingConfigRequest = _reflection.GeneratedProtocolMessageType('GetNeo4jServingConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETNEO4JSERVINGCONFIGREQUEST,
  '__module__' : 'ConfigService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.GetNeo4jServingConfigRequest)
  })
_sym_db.RegisterMessage(GetNeo4jServingConfigRequest)

GetNeo4jServingConfigResponse = _reflection.GeneratedProtocolMessageType('GetNeo4jServingConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETNEO4JSERVINGCONFIGRESPONSE,
  '__module__' : 'ConfigService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.GetNeo4jServingConfigResponse)
  })
_sym_db.RegisterMessage(GetNeo4jServingConfigResponse)


DESCRIPTOR._options = None

_CONFIGSERVICE = _descriptor.ServiceDescriptor(
  name='ConfigService',
  full_name='com.vsu001.ethernet.core.ConfigService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=175,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNeo4jServingConfig',
    full_name='com.vsu001.ethernet.core.ConfigService.GetNeo4jServingConfig',
    index=0,
    containing_service=None,
    input_type=_GETNEO4JSERVINGCONFIGREQUEST,
    output_type=_GETNEO4JSERVINGCONFIGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGSERVICE)

DESCRIPTOR.services_by_name['ConfigService'] = _CONFIGSERVICE

# @@protoc_insertion_point(module_scope)
