# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoreService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CoreService.proto',
  package='com.vsu001.ethernet.core',
  syntax='proto3',
  serialized_options=b'\n com.vsu001.ethernet.core.serviceB\020CoreServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x43oreService.proto\x12\x18\x63om.vsu001.ethernet.core\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n\rUpdateRequest\x12\x1a\n\x12start_block_number\x18\x01 \x01(\x03\x12\x18\n\x10\x65nd_block_number\x18\x02 \x01(\x03\"O\n\x0eUpdateResponse\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xcc\x06\n\x0b\x43oreService\x12k\n\x14UpdateBlockTsMapping\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateBlocks\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x66\n\x0fUpdateContracts\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x61\n\nUpdateLogs\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12k\n\x14UpdateTokenTransfers\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateTokens\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateTraces\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12i\n\x12UpdateTransactions\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x42\x36\n com.vsu001.ethernet.core.serviceB\x10\x43oreServiceProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='com.vsu001.ethernet.core.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_block_number', full_name='com.vsu001.ethernet.core.UpdateRequest.start_block_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_block_number', full_name='com.vsu001.ethernet.core.UpdateRequest.end_block_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=149,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='com.vsu001.ethernet.core.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='com.vsu001.ethernet.core.UpdateResponse.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='com.vsu001.ethernet.core.UpdateResponse.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=230,
)

_UPDATERESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'CoreService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'CoreService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)


DESCRIPTOR._options = None

_CORESERVICE = _descriptor.ServiceDescriptor(
  name='CoreService',
  full_name='com.vsu001.ethernet.core.CoreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=233,
  serialized_end=1077,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateBlockTsMapping',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateBlockTsMapping',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBlocks',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateBlocks',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateContracts',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateContracts',
    index=2,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLogs',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateLogs',
    index=3,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTokenTransfers',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTokenTransfers',
    index=4,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTokens',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTokens',
    index=5,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTraces',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTraces',
    index=6,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTransactions',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTransactions',
    index=7,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CORESERVICE)

DESCRIPTOR.services_by_name['CoreService'] = _CORESERVICE

# @@protoc_insertion_point(module_scope)
