# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CoreService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CoreService.proto',
  package='com.vsu001.ethernet.core',
  syntax='proto3',
  serialized_options=b'\n com.vsu001.ethernet.core.serviceB\020CoreServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x43oreService.proto\x12\x18\x63om.vsu001.ethernet.core\"E\n\rUpdateRequest\x12\x1a\n\x12start_block_number\x18\x01 \x01(\x03\x12\x18\n\x10\x65nd_block_number\x18\x02 \x01(\x03\"&\n\x0eUpdateResponse\x12\x14\n\x0c\x64\x61tabaseName\x18\x01 \x01(\t2\xcc\x06\n\x0b\x43oreService\x12k\n\x14UpdateBlockTsMapping\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateBlocks\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x66\n\x0fUpdateContracts\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x61\n\nUpdateLogs\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12k\n\x14UpdateTokenTransfers\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateTokens\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12\x63\n\x0cUpdateTraces\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x12i\n\x12UpdateTransactions\x12\'.com.vsu001.ethernet.core.UpdateRequest\x1a(.com.vsu001.ethernet.core.UpdateResponse\"\x00\x42\x36\n com.vsu001.ethernet.core.serviceB\x10\x43oreServiceProtoP\x01\x62\x06proto3'
)




_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='com.vsu001.ethernet.core.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_block_number', full_name='com.vsu001.ethernet.core.UpdateRequest.start_block_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_block_number', full_name='com.vsu001.ethernet.core.UpdateRequest.end_block_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=116,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='com.vsu001.ethernet.core.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='com.vsu001.ethernet.core.UpdateResponse.databaseName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'CoreService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'CoreService_pb2'
  # @@protoc_insertion_point(class_scope:com.vsu001.ethernet.core.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)


DESCRIPTOR._options = None

_CORESERVICE = _descriptor.ServiceDescriptor(
  name='CoreService',
  full_name='com.vsu001.ethernet.core.CoreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=159,
  serialized_end=1003,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateBlockTsMapping',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateBlockTsMapping',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateBlocks',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateBlocks',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateContracts',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateContracts',
    index=2,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateLogs',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateLogs',
    index=3,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTokenTransfers',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTokenTransfers',
    index=4,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTokens',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTokens',
    index=5,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTraces',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTraces',
    index=6,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTransactions',
    full_name='com.vsu001.ethernet.core.CoreService.UpdateTransactions',
    index=7,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CORESERVICE)

DESCRIPTOR.services_by_name['CoreService'] = _CORESERVICE

# @@protoc_insertion_point(module_scope)
