spring:
  datasource:
    hivedb:
      username: unused
      password: unused
      url: jdbc:hive2://172.21.148.207:10000/default
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      initial-size: 2
      validation-query: SELECT 1
      validation-query-timeout: 3
      test-on-borrow: true
      max-wait: 60000
      schema: ethernet
  neo4j:
    uri: bolt://172.21.148.207:7687
  data:
    neo4j:
      username: neo4j
      password: test

hadoop:
  fs:
    default-fs: hdfs://namenode:8020
  dfs:
    datanode-use-hostname: true
    client-use-hostname: true

ethernet:
  work-dir: ~/ethernet_work_dir # Do not change, this value is hardcoded
  rpyc-host: 172.21.148.207
  rpyc-port: 18812
  neo4j-container-name: testneo4j
